name: Ruby

on:
  push:
    branches: [master]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", 3.1, 3.2]
        gemfile: ["6.1", "7.0"]
        exclude:
          - ruby: "3.0"
            gemfile: "7.0"
          - ruby: "3.1"
            gemfile: "6.1"
          - ruby: "3.2"
            gemfile: "6.1"
    steps:
      - name: Install packages
        run: |
          sudo apt update -y
          sudo apt install -y libsqlite3-dev

      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rspec
        run: bundle exec rspec
